-- loader.lua

local Features = loadstring(game:HttpGet("https://raw.githubusercontent.com/PittikYalayan/MYLFMenu/main/features.lua"))()

-- UI LIBRARY
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/violin-suzutsuki/LinoriaLib/main/library.lua"))()
local Window = Library:CreateWindow("⚡ MYLF Universal Hack Menu ⚡")

-- 🟢 Player Tab
local PlayerTab = Window:AddTab("Player")
PlayerTab:AddToggle("Fly", {Text = "Fly"}):OnChanged(function(val)
    Features.ToggleFly(val)
end)
PlayerTab:AddSlider("Speed", {Text = "WalkSpeed", Min = 16, Max = 200, Default = 16}):OnChanged(function(val)
    Features.SetSpeed(val)
end)
PlayerTab:AddToggle("Godmode", {Text = "Godmode"}):OnChanged(function(val)
    Features.ToggleGodmode(val)
end)

-- 🎯 Aim Tab
local AimTab = Window:AddTab("Aim")
AimTab:AddToggle("Aimbot", {Text = "Aimbot"}):OnChanged(function(val)
    Features.ToggleAimbot(val)
end)
AimTab:AddSlider("FOV", {Text = "Aimbot FOV", Min = 10, Max = 500, Default = 80}):OnChanged(function(val)
    Features.SetAimbotFov(val)
end)
AimTab:AddToggle("SilentAim", {Text = "Silent Aim"}):OnChanged(function(val)
    Features.ToggleSilentAim(val)
end)
AimTab:AddToggle("NoRecoil", {Text = "No Recoil"}):OnChanged(function(val)
    Features.ToggleNoRecoil(val)
end)
AimTab:AddToggle("NoSpread", {Text = "No Spread"}):OnChanged(function(val)
    Features.ToggleNoSpread(val)
end)

-- 👀 Visuals Tab
local VisualsTab = Window:AddTab("Visuals")
VisualsTab:AddToggle("ESP", {Text = "ESP"}):OnChanged(function(val)
    Features.ToggleESP(val)
end)
VisualsTab:AddToggle("Chams", {Text = "Chams"}):OnChanged(function(val)
    Features.ToggleChams(val)
end)
VisualsTab:AddToggle("Tracers", {Text = "Tracers"}):OnChanged(function(val)
    Features.ToggleTracers(val)
end)
VisualsTab:AddToggle("RainbowESP", {Text = "Rainbow ESP"}):OnChanged(function(val)
    Features.ToggleRainbowESP(val)
end)

-- ⚙️ Misc Tab
local MiscTab = Window:AddTab("Misc")
MiscTab:AddToggle("Bhop", {Text = "Bunny Hop"}):OnChanged(function(val)
    Features.ToggleBhop(val)
end)
MiscTab:AddToggle("FOVChanger", {Text = "FOV Changer"}):OnChanged(function(val)
    Features.ToggleFov(val)
end)
MiscTab:AddSlider("FOV", {Text = "FOV Value", Min = 70, Max = 120, Default = 90}):OnChanged(function(val)
    Features.SetFov(val)
end)
MiscTab:AddToggle("ThirdPerson", {Text = "Third Person"}):OnChanged(function(val)
    Features.ToggleThirdPerson(val)
end)
